const menu = [
  {
    id: 1,
    title: 'Cumin Seeds',
    category: 'Masala',
    price: 15.99,
    img: './images/cumin-seeds.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Premium Turmeric Powder',
    category: 'Masala',
    price: 13.99,
    img: './images/premium-turmeric-powder.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'Red Chilli Powder',
    category: 'Masala',
    price: 6.99,
    img: './images/red-chilli-powder.png',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'Black Mustard Seeds',
    category: 'Masala',
    price: 20.99,
    img: './images/black-mustard-seeds.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Khada/Garam Masala',
    category: 'Masala',
    price: 22.99,
    img: './images/Khada-Garam-Masala.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'Badam',
    category: 'Dry Fruits',
    price: 18.99,
    img: './images/Badam.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Kaju',
    category: 'Dry Fruits',
    price: 8.99,
    img: './images/Cashew-Nut.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Brown Whole Kharik',
    category: 'Dry Fruits',
    price: 12.99,
    img: './images/brown-whole-kharik1.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Kismis',
    category: 'Dry Fruits',
    price: 16.99,
    img: './images/kismis.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'Indian Toor Dal',
    category: 'Premium Dals',
    price: 16.99,
    img: './images/indian-toor-dal.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: 'Masoor Dal',
    category: 'Premium Dals',
    price: 16.99,
    img: './images/Masoor-dal.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: 'Chana Dal',
    category: 'Premium Dals',
    price: 16.99,
    img: './images/Chana-Dal.png',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: 'Kabuli Chana',
    category: 'Premium Dals',
    price: 16.99,
    img: './images/Kabuli-chana.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
